version: '3.7'

services:
  express-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: express-api-dev
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn dev
    env_file:
      - .env.development
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 'rootroot'
volumes:
  db-data:
